---
clone_folder: c:\project\opencpn
shallow_clone: false
clone_depth: 10

image:
  - Visual Studio 2022

platform:
  - Win32

configuration: RelWithDebInfo

install:
  - set "VS_BASE=C:\Program Files\Microsoft Visual Studio\2022"
  - call "%VS_BASE%\Community\VC\Auxiliary\Build\vcvars32.bat"

  - cmd: python --version

build_script:
  - call ci\appveyor.bat

deploy_script:
  - |
    cd %APPVEYOR_BUILD_FOLDER%\ci
    "\Program Files\Git\bin\bash" appveyor-upload.sh
