= Compiling on Windows

== 5.8.0 Fast Track

From version 5.8.0 the windows build system has been revised.
The fast track described here is simplified and without all the options
provided by the procedure described from next section.

Steps to to make a build:

. Get Visual Studio Community 2022,  either the command line tools or the
  complete environment, from https://visualstudio.microsoft.com/vs/community/
. Install the choco package manager, https://chocolatey.org/install
. Clone the sources and move into them: +

       > git clone https://github.com/OpenCPN/OpenCPN.git
       > cd OpenCPN

. Run the script _buildwin\win_deps.bat_. First time script installs programs
  and should be invoked with administrative privileges using the Visual Studio
  Command Line Interface. Following runs can (i. e., should) be run as a
  regular user.
. Run the script _ci\appveyor.bat_. This will configure the project using
  cmake and make an initial build.

After the first build, new builds can be done using in the _build_ directory
using:
```
    > cmake --build . --target opencpn --config Release
```

*Notes:*

* `--target opencpn` creates the main executable. Other targets which can be
  built includes

** `--target opencpn-cmd` -- Command line tool
** `--target tests` -- Command line unit tests
** `--target package` -- NSIS installer

* It is perfectly possible to use `--config Debug` to create an executable with
  debugging symbols etc. However, doing so might make the plugins in the
  catalog incompatible if it is not possible to load optimized libraries into
  a opencpn debug build. FIXME(leamas): what is the situation?
* _win_deps.bat_ stores files in the _cache_ directory. This can be removed
  safely,  it is re-created from scratch by _win_deps.bat_
* The correct options to invoke cmake manually can be found  in
  _ci\appveyor.bat_
* Both _win_deps.bat_ and _appveyor.bat_ are used in the ci builds and should
  thus be reasonably tested. However, user environment (in particular PATH))
  can make them fail.

== Complete builds using Visual Studio

The steps here describe how to make a complete build in Visual Studio,
including full source debugging with Intellisense(R).
The setup is based on the script _buildwin\winConfig.bat_.
This script can be used to create a local build environment for OpenCPN

Here are some basic steps that are known to work.
There are probably other ways to do this, but this is the way that works for
me.

. Install Visual Studio 2022 Community Edition
  https://visualstudio.microsoft.com/downloads/. Be sure to select components:
+
* [*] ```Desktop development with C++```
* [*] ```C++ CMake tools for windows```
+
. Install git for Windows: https://git-scm.com/download/win
. Open _x86 Native Tools Command Prompt for Visual Studio 2022_
. Create folder where you want to work with OpenCPN sources, something
   like this:
+
[,console]
----
$ mkdir \Users\myname\src
$ cd \Users\myname\src
----
+
. Clone Opencpn, for example:
+
[,console]
----
$ cd \Users\myname\src
$ git clone https://github.com/opencpn/opencpn
$ cd opencpn
----
+
. Set up local build environment by executing
   `buildwin\winConfig.bat`
. OpenCPN can now be built on the command line or directly from Visual Studio.
  For example, to make a Debug build:
+
[,console]
----
$ .\buildwin\configdev.bat
$ msbuild /noLogo /m -p:Configuration=Debug;Platform=Win32 opencpn.sln
$ .\opencpn.sln
----
+
. The most common workflow is to use Visual Studio GUI to build and debug. Configure the
  environment using configdev.bat then open solution file (type solution file
  name at VS command prompt). Example:
+
[,console]
----
$ .\buildwin\configdev.bat
$ .\opencpn.sln
----
+
Start building and debugging in Visual Studio. Available targets include:

    - opencpn -- Build  main executable
    - package -- Build NSIS installer
    - opencpn-cmd  -- Build command line tool
    - tests -- Build unit tests.
    - run-tests -- Run unit tests

Available Visual Studio Win32 configurations include:

    - Debug -- Build with full debugging sumbols and source info
    - RelWithDebInfo  -- Build with limited debug/source info (faster)
    - Release -- Build with no debug or source info (fastest code)
    - MinSizeRel -- Build with no debug/source info (smallest executable)

*Notes:*

* We recommend using msbuild as the command line builder instead of CMake.  The reasons:
** msbuild is faster than CMake or CMake w/Ninja
** msbuild gives full access to every type of build and project
** CMake requires a configure step to change the build type (Release, Debug, etc.)
** as it turns out, by default, cmake uses msbuild under the covers

* We also recommend installing the latest powershell version.  It is much more
powerful and visually friendly.  Install like this:
+
[,console]
----
$ winget install --id Microsoft.Powershell --source winget
----
* It is important to have a 'clean' environment.
** Make sure there are no permanent environment variables related to
   wxWidgets (these all begin with WX).  If you have any it is safe to delete them.
** Remove all references to wxWidgets from the permanent PATH environment variables.
** It is ok to install tools such as NSIS but not required.  Any tools required to
   build or package will be automatically installed by the 'buildwin\winConfig.bat' script.
** The 'winConfig.bat' script does not install Visual Studio. Neither does it install
   tools such as git or npm as these are not used by the build system.
* The 'winConfig.bat' script sets up 4 folders beneath the 'build' folder that house 4 different
   runtime configurations based on the 4 standard build types. Since each configuration is a
   standalone local instance of OpenCPN, they have to be run in 'portable' mode. 
   To manually launch a particular configruation (e.g. RelWithDebInfo) set the working
   folder to OpenCPN\build\RelWithDebInfo then launch OpenCPN in portable mode. For example:
+
[,console]
----
$ .\buildwin\configdev.bat
$ cd .\RelWithDebInfo
$ .\opencpn -p
----
+

* The 'winConfig.bat' script also has the ability to automatically clean and/or build various
  configuations.  Any or all command line options can be used at the same time.  Note that 
  it can take some time to complete if you use every command line option.  Command line options
  are all lowercase and case sensitive. The command line options are as follows:
+
[,console]
----
 --clean :: cleans all files from the build folder then sets up the build system anew
 --release :: builds a Release configuration
 --relwithdebuinfo :: builds a RelWithDebInfo configuration
 --debug :: builds a Debug configuration
 --minsizerel :: builds MinSizeRel configuration
----
+

* Useful msbuild command line examples follow. Type these commands after running
  '.\buildwin\configdev.bat' from the root opencpn git managed folder.
** Create an executable Windows installer for a fully debuggable version
+
[,console]
----
$ msbuild  /m --target:Build -p:Configuration=Debug;Platform=Win32 PACKAGE.vcxproj
----
+
** Clean and build every project to create debug build
+
[,console]
----
$ msbuild /m -t:Rebuild -p:Configuration=Debug opencpn.sln
----
+
** Clean and build every project to create Release with debug info
+
[,console]
----
$ msbuild /m -t:Rebuild -p:Configuration=RelWithDebInfo All_BUILD.vcxproj
----
+
** Build debug version of OpenCPN core
+
[,console]
----
$ msbuild /m -t:Build -p:Configuration=Debug opencpn.vcxproj
----
+
** Clean opencpn-cmd.exe
+
[,console]
----
$ msbuild /m -t:Clean -p:Configuration=Debug opencpn-cmd.vcxproj
----
+
** Clean and build chart downloader plugin
+
[,console]
----
$ msbuild /m -t:Rebuild -p:Configuration=Debug plugins\chartdldr_pi\chartdldr_pi.vcxproj
----
+
* You can use still use CMake if you like:
+
[,console]
----
$ cmake -DCMAKE_BUILD_TYPE=Debug ..
$ cmake --build . --config Debug --target Package
----
+
will create a full debug executable installer
* This will clean and build a Release build
+
[,console]
----
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ cmake --build . --config Release --clean-first
----
+
* It is possible to `attach` the Visual Studio debugger to a running instance.
 This is useful if you create an installer, install and run OpenCPN from the start menu.
 Once OpenCPN is running in its native enviroment the Visual Studio debugger can attach
 itself to the running instance.  Find ```Attach to process...``` under the Debug menu item.
