= Compiling on Windows

== 5.8.0 Fast Track

From version 5.8.0 the windows build system has been revised.
The fast track described here is simplified and without all the options
provided by the procedure described from next section.

Steps to to make a build:

. Get Visual Studio Community 2022,  either the command line tools or the
  complete environment, from https://visualstudio.microsoft.com/vs/community/
. Install the choco package manager, https://chocolatey.org/install
. Clone the sources and move into them: +

       > git clone https://github.com/OpenCPN/OpenCPN.git
       > cd OpenCPN

. Run the script _buildwin\win_deps.bat_. First time script installs programs
  and should be invoked with administrative privileges using the Visual Studio
  Command Line Interface. Following runs can (i. e., should) be run as a
  regular user.
. Run the script _ci\appveyor.bat_. This will configure the project using
  cmake and make an initial build.

After the first build, new builds can be done using in the _build_ directory
using:
```
    > cmake --build . --target opencpn --config Release
```

*Notes:*

* `--target opencpn` creates the main executable. Other targets which can be
  built includes

** `--target opencpn-cmd` -- Command line tool
** `--target tests` -- Command line unit tests
** `--target package` -- NSIS installer

* It is perfectly possible to use `--config Debug` to create an executable with
  debugging symbols etc. However, doing so might make the plugins in the
  catalog incompatible if it is not possible to load optimized libraries into
  a opencpn debug build. FIXME(leamas): what is the situation?
* _win_deps.bat_ stores files in the _cache_ directory. This can be removed
  safely,  it is re-created from scratch by _win_deps.bat_
* The correct options to invoke cmake manually can be found  in
  _ci\appveyor.bat_
* Both _win_deps.bat_ and _appveyor.bat_ are used in the ci builds and should
  thus be reasonably tested. However, user environment (in particular PATH))
  can make them fail.

== Complete builds using Visual Studio

The steps here describes how to make a complete build in Visual Studio,
inclusive debugging.
The setup is based on the script _buildwin\setupLocalWinBuild.bat_.
This script can be used to create a local build environment for OpenCPN

Here are some basic steps that are known to work.
There are probably other ways to do this, but this is the way that works for
me.

1. Install Visual Studio 2022 Community Edition
   https://visualstudio.microsoft.com/downloads/
2. Install git for Windows: https://git-scm.com/download/win
3. Open _x86 Native Tools Command Prompt for Visual Studio 2022_
4. Create folder where you want to work with OpenCPN sources, something
   like+

        mkdir \Users\myname\src
        cd \Users\myname\src

5. Clone Opencpn, for example

        cd \Users\myname\src
        git clone https://github.com/opencpn/opencpn
        cd opencpn

6. Set up local build environment by executing
   `buildwin\setupLocalWinBuild.bat`
7. OpenCPN can now be built on the command line. Debug, Release and
   RelWithDebinfo configurations are available. For example, to make a
   Debug build:

       buildwin\configdev.bat && cd build
       msbuild /noLogo /m -p:Configuration=Debug -p:Platform=Win32 opencpn.sln
       devenv opencpn.sln

8. Open solution file (type solution file name at VS command prompt)
        Example: .\build\opencpn.sln

Start building and debugging in Visual Studio. Available targets includes

- opencpn -- Build  main executable
- package -- Build NSIS installer
- opencpn-cmd  -- Build command line tool
- tests -- Build unit tests.
- run-tests -- Run unit tests
