name: OpenCPN_wxTest

on:
  push:
    branches:
    - wxTest

  
jobs:
  OpenCPN_wxTest:
    runs-on: [self-hosted, Windows, X64]
    env:
      # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
      BUILD_TYPE: RelWithDebInfo
      WXWIN: C:\OA\WXWIDGETS
      WXDIR: C:\OA\WXWIDGETS
      wxWidgets_LIB_DIR: C:\OA\WXWIDGETS\lib\vc142_dll
      wxWidgets_ROOT_DIR: C:\OA\WXWIDGETS

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup
      shell: powershell
      working-directory: ${{github.workspace}}
      run: |
        echo ${Env:WXWIN}
        echo ${(env.WXWIN)}
        mkdir ${{github.workspace}}/build
        echo "C:\Program Files\7-Zip" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files (x86)\Poedit\GettextTools\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
    - name: Get Dependencies
      shell: powershell
      run: |
        Remove-Item * -Recurse -Path ${{github.workspace}}\buildwin\wxWidgets -Force -ErrorAction:Ignore
        xcopy /C ${(Env.wxWidgets_LIB_DIR)}\*u_*.dll ${{github.workspace}}\buildwin\wxWidgets
        xcopy /C ${(Env.wxWidgets_LIB_DIR)}\*u_*.pdb ${{github.workspace}}\buildwin\wxWidgets
        New-Item ${{github.workspace}}\buildwin\wxWidgets\locale -ErrorAction:Ignore
        xcopy /C ${(Env.WXDIR)}\locale\*.mo ${{github.workspace}}\buildwin\wxWidgets\locale
        xcopy /C ${(Env.WXDIR)}\locale\*.pot ${{github.workspace}}\buildwin\wxWidgets\locale
        Invoke-WebRequest https://download.opencpn.org/s/oibxM3kzfzKcSc3/download -OutFile OpenCPN_buildwin-4.99a.7z
        7z x -y OpenCPN_buildwin-4.99a.7z -o${{github.workspace}}\buildwin
    - name: CMake Configure
      shell: powershell
      working-directory: ${{github.workspace}}/build
      run: cmake -Wno-dev "-AWin32" -G"Visual Studio 16 2019" -T "v142" -DOCPN_CI_BUILD=ON -DCMAKE_SYSTEM_VERSION=8.1 -DCMAKE_CXX_FLAGS="/MP /EHsc /DWIN32" -DCMAKE_C_FLAGS="/MP" -DOCPN_ENABLE_SYSTEM_CMD_SOUND=ON -DCMAKE_EXE_LINKER_FLAGS=""/SUBSYSTEM:WINDOWS"  " -DCMAKE_MODULE_LINKER_FLAGS=""/SUBSYSTEM:WINDOWS"  " ..
      
    - name: Cmake Build
      shell: powershell
      working-directory: ${{github.workspace}}/build
      run: |
        cmake --build . --config ${{env.BUILD_TYPE}}
        cmake --build . --config ${{env.BUILD_TYPE}}
      
    - name: Create Package
      if: success()
      shell: powershell
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}} --target Package
      
    - uses: actions/upload-artifact@v2.2.4
      with:
        name:  OpenCPN_5.5.0
        path: ${{github.workspace}}/build/*.exe
