name: OpenCPN

on:
  push:
    branches: [ runner ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  WXWIN: C:\wxWidgets-3.1.2
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - uses: actions/checkout@v2
    
    - name: Make folder
      shell: powershell
      working-directory: ${{github.workspace}}
      run: mkdir ${{github.workspace}}/build
      
    - name: Download wxWidgets version 3.1.2
      shell: powershell
      run: |
        echo $env:path
        echo $env:GITHUB_PATH
        echo $env:GITHUB_ENV
        echo "C:\Program Files\7-Zip" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo $env:WXWIN | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo $env:GITHUB_PATH
        Invoke-WebRequest https://download.opencpn.org/s/E2p4nLDzeqx4SdX/download -OutFile wxWidgets-3.1.2.7z

    - name: Unzip wxWidgets
      shell: cmd
      run: |
        echo $env:GITHUB_ENV
        echo "wxWidgets_ROOT_DIR=%WXWIN%" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo $env:GITHUB_ENV
        echo "wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo $env:GITHUB_ENV
        7z x wxWidgets-3.1.2.7z -o%WXWIN% > null
      
    - name: Get Dependencies
      shell: powershell
      working-directory: ${{github.workspace}}/build
      run: Invoke-WebRequest https://download.opencpn.org/s/oibxM3kzfzKcSc3/download -OutFile OpenCPN_buildwin-4.99a.7z

    - name: Explode
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: 7z x -y OpenCPN_buildwin-4.99a.7z -o${{github.workspace}}\buildwin

    - name: CMake Configure
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: |
        del .\CMakeCache.txt
        cmake -Wno-dev "-AWin32" -G"Visual Studio 16 2019" -T "v142" -D CMAKE_SYSTEM_VERSION=8.1 -D CMAKE_CXX_FLAGS="/MP /EHsc /DWIN32" -D CMAKE_C_FLAGS="/MP" -D OCPN_ENABLE_SYSTEM_CMD_SOUND=ON -D CMAKE_EXE_LINKER_FLAGS=""/SUBSYSTEM:WINDOWS"  " -D CMAKE_MODULE_LINKER_FLAGS=""/SUBSYSTEM:WINDOWS"  " -D CMAKE_SHARED_MODULE_LINKER_FLAGS=""/SUBSYSTEM:WINDOWS"  " ..
      
    - name: Cmake Build
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Cmake Build again
      if: ${{ failure() }}
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

