name: OpenCPN

on:
  push:
    branches: [ runner ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - uses: actions/checkout@v2
    
    - name: Make folder
      shell: cmd
      working-directory: ${{github.workspace}}
      run: mkdir ${{github.workspace}}/build
      
    - name: Get Dependencies
      shell: powershell
      working-directory: ${{github.workspace}}/build
      run: powershell -Command Start-FileDownload https://download.opencpn.org/s/oibxM3kzfzKcSc3/download -FileName OpenCPN_buildwin-4.99a.7z &&

    - name: Explode
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: 7z x -y OpenCPN_buildwin-4.99a.7z -oc:\project\opencpn\buildwin &&

    - name: Explode
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: cmake -Wno-dev "-AWin32" -G"Visual Studio 16 2019" -T "v142" -D CMAKE_SYSTEM_VERSION=8.1 -D CMAKE_CXX_FLAGS="/MP /EHsc /DWIN32" -D CMAKE_C_FLAGS="/MP" -D OCPN_ENABLE_SYSTEM_CMD_SOUND=ON -D CMAKE_EXE_LINKER_FLAGS=""/SUBSYSTEM:WINDOWS"  " -D CMAKE_MODULE_LINKER_FLAGS=""/SUBSYSTEM:WINDOWS"  " -D CMAKE_SHARED_MODULE_LINKER_FLAGS=""/SUBSYSTEM:WINDOWS"  " ..
      
    - name: Build
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

