name: OpenCPN

on:
  push:
    branches: [ runner ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  WXWIN: C:\wxWidgets-3.1.2
  WXDIR: C:\wxWidgets-3.1.2
  wxWidgets_LIB_DIR: C:\wxWidgets-3.1.2\lib\vc_dll
  wxWidgets_ROOT_DIR: C:\wxWidgets-3.1.2

jobs:
  OpenCPN_runner:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      shell: powershell
      working-directory: ${{github.workspace}}
      run: |
        mkdir ${{github.workspace}}/build
        echo "C:\Program Files\7-Zip" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files (x86)\Poedit\GettextTools\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Get Dependencies
      shell: powershell
      run: |
        Remove-Item -path ${{env.WXWIN}} -force -Recurse
        Invoke-WebRequest https://download.opencpn.org/s/E2p4nLDzeqx4SdX/download -OutFile wxWidgets-3.1.2.7z
        7z x -y wxWidgets-3.1.2.7z -o${{env.WXWIN}}
        Remove-Item wxWidgets-3.1.2.7z
        Invoke-WebRequest https://download.opencpn.org/s/oibxM3kzfzKcSc3/download -OutFile OpenCPN_buildwin-4.99a.7z
        7z x -y OpenCPN_buildwin-4.99a.7z -o${{github.workspace}}\buildwin
        Remove-Item OpenCPN_buildwin-4.99a.7z

    - name: CMake Configure
      shell: powershell
      working-directory: ${{github.workspace}}/build
      run: cmake -T v141_xp -AWin32 -DWX_LIB_DIR="${{env.wxWidgets_LIB_DIR}}" -DOCPN_CI_BUILD=ON ..

    - name: Cmake Build
      shell: powershell
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Create Package
      if: success()
      shell: powershell
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}} --target Package

    - uses: actions/upload-artifact@v2.2.4
      with:
        name:  OpenCPN_5.5.0
        path: ${{github.workspace}}/build/*.exe
